### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MattGames123** [mkdeosm/mk_cum#2]
it said my pc is old as fuck pls fix this isntt opmtimzed plsiok,4gp y8wv emuwoj evevevevevevomf

**Comment by mkdeosm** [comment]
It is possible that you have a problem with the compiler. This program only prints text to the console. even a calculator can pull this program! so most likely the problem is in the utilities. did you compile cum? if not, then I will make a make-up specially for you :)

**Comment by MattGames123** [comment]
Yay haappy cum times
Less go get some cum

**Comment by mkdeosm** [comment]
yea hahahah!!!
